name: gplately-pygmt
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - gplately
  - pygmt
  - jupyterlab
  - panel
  - matplotlib
  - cartopy
  - xarray
  - pandas
  - numpy
  - shapely
  - geopandas
  - pyarrow
  - imageio
  - ffmpeg
  - pip
